-- Persistent, collision-proof P6 resource short names per company.
-- Adds:
-- - company_resource_sequences
-- - resource_registry
-- - rate_card_entries.rsrc_short_name (backfilled for existing rows)

-- 1) Sequence table
CREATE TABLE IF NOT EXISTS "company_resource_sequences" (
  "id" TEXT NOT NULL,
  "company_id" TEXT NOT NULL,
  "prefix" VARCHAR(32) NOT NULL,
  "last_number" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "company_resource_sequences_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "company_resource_sequences_company_id_prefix_key"
  ON "company_resource_sequences"("company_id", "prefix");

CREATE INDEX IF NOT EXISTS "company_resource_sequences_company_id_idx"
  ON "company_resource_sequences"("company_id");

-- 2) Registry table
CREATE TABLE IF NOT EXISTS "resource_registry" (
  "id" TEXT NOT NULL,
  "company_id" TEXT NOT NULL,
  "prefix" VARCHAR(32) NOT NULL,
  "rsrc_short_name" VARCHAR(64) NOT NULL,
  "resource_type" VARCHAR(120) NOT NULL,
  "resource_name" VARCHAR(255) NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "resource_registry_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "resource_registry_company_id_rsrc_short_name_key"
  ON "resource_registry"("company_id", "rsrc_short_name");

CREATE UNIQUE INDEX IF NOT EXISTS "resource_registry_company_id_prefix_resource_type_resource_name_key"
  ON "resource_registry"("company_id", "prefix", "resource_type", "resource_name");

CREATE INDEX IF NOT EXISTS "resource_registry_company_id_idx"
  ON "resource_registry"("company_id");

-- 3) Add persisted short name onto rate card entries (backfill existing)
ALTER TABLE "rate_card_entries"
  ADD COLUMN IF NOT EXISTS "rsrc_short_name" VARCHAR(64);

-- Backfill: deterministic within each company by (resource_name, resource_type).
WITH ranked AS (
  SELECT
    id,
    company_id,
    ROW_NUMBER() OVER (PARTITION BY company_id ORDER BY resource_name ASC, resource_type ASC) AS rn
  FROM rate_card_entries
)
UPDATE rate_card_entries r
SET rsrc_short_name = 'PLARES-' || ranked.rn::text
FROM ranked
WHERE r.id = ranked.id
  AND (r.rsrc_short_name IS NULL OR btrim(r.rsrc_short_name) = '');

-- Ensure not null after backfill.
ALTER TABLE "rate_card_entries"
  ALTER COLUMN "rsrc_short_name" SET NOT NULL;

CREATE INDEX IF NOT EXISTS "rate_card_entries_company_id_rsrc_short_name_idx"
  ON "rate_card_entries"("company_id", "rsrc_short_name");

-- 4) Seed registry from current rate card entries (id generated by app; keep placeholder ids here).
-- NOTE: If you need DB-generated ids, add an extension + default; otherwise prisma will write ids for new rows.
INSERT INTO resource_registry (id, company_id, prefix, rsrc_short_name, resource_type, resource_name)
SELECT
  'seed_' || r.id,
  r.company_id,
  'PLARES',
  r.rsrc_short_name,
  r.resource_type,
  r.resource_name
FROM rate_card_entries r
ON CONFLICT (company_id, rsrc_short_name) DO NOTHING;

-- 5) Seed/advance sequences per company to max reserved number.
INSERT INTO company_resource_sequences (id, company_id, prefix, last_number)
SELECT
  'seq_seed_' || company_id,
  company_id,
  'PLARES',
  MAX(CAST(NULLIF(split_part(rsrc_short_name, '-', 2), '') AS INTEGER))
FROM rate_card_entries
GROUP BY company_id
ON CONFLICT (company_id, prefix) DO UPDATE
SET last_number = GREATEST(company_resource_sequences.last_number, EXCLUDED.last_number);

